import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'install',
    'quick-start',
    'usage',
    {
      type: 'category',
      label: 'Rules',
      link: {type: 'doc', id: 'rules/index'},
      items: [{type: 'autogenerated', dirName: 'rules'}],
    },
    'custom-policies',
    'security',
  ],
};

export default sidebars;
