//! Embeds the shared Rego policies at compile time.
//!
//! The rules live in `rules/policy/` at the repo root and are the single source
//! of truth for both the Go and the Rust linter. Discovering them here rather
//! than listing them in source means a new .rego file is picked up by both
//! implementations without touching Rust.

use std::{env, fs, path::{Path, PathBuf}};

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let policy_dir = manifest
        .join("../../rules/policy")
        .canonicalize()
        .expect("rules/policy not found relative to augur-core");

    let mut files = Vec::new();
    collect(&policy_dir, &mut files);
    files.sort();
    assert!(!files.is_empty(), "no .rego policies found in {}", policy_dir.display());

    let mut out = String::from(
        "/// (module name, source) for every bundled policy, generated by build.rs.\n\
         pub static POLICIES: &[(&str, &str)] = &[\n",
    );
    for path in &files {
        println!("cargo:rerun-if-changed={}", path.display());
        let name = path
            .strip_prefix(&policy_dir)
            .unwrap()
            .to_string_lossy()
            .replace('\\', "/");
        out.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            name,
            path.to_string_lossy()
        ));
    }
    out.push_str("];\n");

    println!("cargo:rerun-if-changed={}", policy_dir.display());
    fs::write(
        PathBuf::from(env::var("OUT_DIR").unwrap()).join("policies.rs"),
        out,
    )
    .unwrap();
}

fn collect(dir: &Path, out: &mut Vec<PathBuf>) {
    for entry in fs::read_dir(dir).expect("reading policy dir") {
        let path = entry.expect("policy dir entry").path();
        if path.is_dir() {
            collect(&path, out);
        } else if path.extension().is_some_and(|e| e == "rego")
            && !path.file_name().unwrap().to_string_lossy().ends_with("_test.rego")
        {
            out.push(path);
        }
    }
}
